name: Build Verona APK

on:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build APK
        id: build
        uses: flet-dev/flet-build-action@v1
        with:
          target: apk
          runner-python-version: "3.11"
          bundled-python-version: "3.11"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Verona-App-APK
          path: |
            *.apk
            dist/*.apk
            output/*.apk
            build/apk/*.apk
          if-no-files-found: ignore
